services:
  - type: web
    name: merakarcha-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: DATABASE_URL
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: SPLITWISE_API_KEY
        sync: false
      - key: SPLITWISE_USER_ID
        sync: false
      - key: SPLITWISE_GROUP_ID
        sync: false
      - key: SPLITWISE_DATED_AFTER
        sync: false
      - key: CURRENCY_SYMBOL
        sync: false
