# Generated by Django 6.0.6 on 2026-06-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_alter_expense_splitwise_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("synced_at", models.DateTimeField()),
                ("imported", models.IntegerField()),
                ("skipped", models.IntegerField()),
            ],
            options={
                "ordering": ["-synced_at"],
            },
        ),
    ]
