# Generated by Django 6.0.6 on 2026-06-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0003_synclog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="payment_method",
        ),
        migrations.AddField(
            model_name="expense",
            name="paid_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
