# Generated by Django 6.0.6 on 2026-06-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0004_remove_expense_payment_method_expense_paid_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="mode",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
